sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shilpa/docker-react -f Dockerfile.dev .

script:
  - docker run shilpa/docker-react npm run test -- --coverage
